#!/usr/bin/env ruby

require "kusa"
require 'date'
require 'time'
require 'thor'

class KusaCLI < Thor
  package_name 'kusa'
  default_command :www
  option 'max-commit-per-day', :type=> :numeric, :desc => 'A natural number of 2 or more', :default => 10
  map %w(-v --version) => :version

  desc 'www [--from=FROM-DATE] [--to=TO-DATE]', 'lol'
  method_option 'from', :banner => 'FROM-DATE', :desc => 'Processing start date'
  method_option 'to',   :banner => 'TO-DATE',   :desc => 'Processing end date'
  def www
    now = Time.now
    from = options['from'] ? Time.parse(options['from']) : now - 60*60*24*365
    to = options['to'] ? Time.parse(options['to']) : now

    (from.to_datetime..to.to_datetime).each do |date|
      1.upto(rand(2..options['max-commit-per-day'])) {|i| commit(date) }
    end
  end

  desc 'version', 'Print version'
  def version
    STDOUT.puts Kusa::VERSION
    exit 0
  end

  private

  def commit(date=DateTime.now)
    system({"GIT_COMMITTER_DATE" => date.to_s},
           "git", "commit", "--allow-empty", "--date=#{date}", "-m 'kusa.rb: #{date}'")
  end
end

KusaCLI.start(ARGV)
